# Estado de los equipos
simulacion=true;

# Archivo de tipos de equipo
tipoEquipo=data/tipo_equipo.txt

# Path al archivo de tipos de cable
tipoCable=data/tipo_cable.txt

# Ruta al archivo de tipos de puerto
tipoPuerto=data/tipo_puerto.txt

# Ruta al archivo de equipos
equipo=data/equipo.txt

# Archivo de ubicaciones
ubicacion=data/ubicacion.txt

# Ruta al archivo de conexiones
conexion=data/conexion.txt
